config/routes.rb
Rails.application.routes.draw do
  devise_scope(:user) { get '/users/sign_out' => 'devise/sessions#destroy' }
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'lensmodels#index'

  concern :commentable do
    resources :comments
  end

  resources :lensmodels,   concerns: :commentable, shallow: true
  resources :lensitems,    concerns: :commentable
  resources :cameramodels, concerns: :commentable
  resources :cameraitems,  concerns: :commentable
  resources :users,        concerns: :commentable, only: [:index, :show]
  resources :attachments, only: [:destroy]
end

app/models/cameraitem.rb
class Cameraitem < ActiveRecord::Base
  include Commentable

  belongs_to :user
  belongs_to :cameramodel

  validates :price, presence: true, numericality:  { greater_than: 0 }
  validates :cameramodel_id, presence: true
  validates :user_id, presence: true
  # validates :description, length: { minimum: 2, maximum: 1000 }

  after_create  { increase_quantity }
  after_destroy { decrease_quantity }

  mount_uploader :image, ImageUploader

  private

  def increase_quantity
    cameramodel.update_attributes(quantity: cameramodel.quantity + 1)
  end

  def decrease_quantity
    cameramodel.update_attributes(quantity: cameramodel.quantity - 1)
  end
end

app/controllers/cameraitems_controller.rb
class CameraitemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_cameraitem, only: [:show, :edit, :update, :destroy]

  authorize_resource
  # respond_to :js, :json

  def index
    respond_with(@cameraitems = Cameraitem.all)
  end

  def show
    @cameramodel = @cameraitem.cameramodel
    respond_with @cameraitem
  end

  def new
    @cameramodels = Cameramodel.order("name")
    respond_with(@cameraitem = Cameraitem.new)
  end

  def edit
  end

  def create
    respond_with(@cameraitem = Cameraitem.create(cameraitem_params))
  end

  def update
    @cameraitem.update(cameraitem_params)
    respond_with @cameraitem
  end

  def destroy
    @cameraitem.destroy if @cameraitem.user_id == current_user.id
    respond_with @cameraitem
  end

  private

  def load_cameraitem
    @cameraitem = Cameraitem.find(params[:id])
  end

  def cameraitem_params
    params.require(:cameraitem).permit(:cameramodel_id, :price, :description, :image, :used).merge(user_id: current_user.id)
  end
end

app/helpers/cameraitems_helper.rb
module CameraitemsHelper
end

app/views/cameraitems/_form.html.slim
div
  = f.label :cameramodel_id
  = f.collection_select :cameramodel_id, @cameramodels, :id, :fullname, { prompt: true }
  = f.label "Видимый"
  = f.check_box :visible
div
  = f.label "Цена:"
  = f.number_field :price, size: 61
  = f.label "Б/у"
  = f.check_box :used
div
  = f.label "Описание:"
  = f.text_field :description, size: 61
div
  = f.label "Изображение:"
  = f.file_field :image

app/views/cameraitems/edit.html.slim
= form_for @cameraitem do |f|
  = render partial: "form", locals: { f: f }
  = f.submit "Изменить камеру", class: 'btn btn-success btn-sm'

app/views/cameraitems/index.html.slim
- unless @cameraitems.empty?
  h1 Фотоаппараты:
  table class="table" id="cameraitems"
    thead
      tr
        th Фото:
        th Mount:
        th Brand:
        th Name:
        th Цена:
    tbody
      - @cameraitems.each do |cameraitem|
        tr
          td = image_tag cameraitem.image.thumb
          td = cameraitem.cameramodel.mount
          td = cameraitem.cameramodel.brand
          td = link_to (cameraitem.cameramodel.name), cameraitem_path(cameraitem)
          td = link_to (cameraitem.price), cameraitem_path(cameraitem)
- else
  h4 Нет фотоаппаратов в продаже!

app/views/cameraitems/new.html.slim
h1 Продать фотоаппарат:
= form_for @cameraitem do |f|
  = render partial: "form", locals: { f: f }
  .cameraitem-errors
  br
    = f.submit "Продать камеру", class: 'btn btn-success btn-sm'

app/views/cameraitems/show.html.slim
h2
  i &nbsp;
  = link_to ('<< '), cameramodel_path(@cameramodel)
  = (@cameramodel.mount + ' ' + @cameramodel.brand + ' ' + @cameramodel.name)
br
- if can?(:update, @cameraitem)
  = link_to "Редактировать?", edit_cameraitem_path(@cameraitem)
  i &nbsp; или &nbsp;
  = link_to "Удалить?", @cameraitem, method: :delete, data: {confirm: "Подтверждение удаления"}
div
  i Цена:&nbsp;
  = @cameraitem.price
  i &nbsp рублей
div
  i Б.у.:&nbsp;
  = @cameraitem.used
div
  i Описание:&nbsp;
  = @cameraitem.description
div
  i email:&nbsp
  = link_to (@cameraitem.user.email), user_path(@cameraitem.user_id)
div
  = image_tag @cameraitem.image.normal
= render 'comments/list', parent: @cameraitem