config/routes.rb
Rails.application.routes.draw do
  devise_scope(:user) { get '/users/sign_out' => 'devise/sessions#destroy' }
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'lensmodels#index'

  concern :commentable do
    resources :comments
  end

  resources :lensmodels,   concerns: :commentable, shallow: true
  resources :lensitems,    concerns: :commentable
  resources :cameramodels, concerns: :commentable
  resources :cameraitems,  concerns: :commentable
  resources :users,        concerns: :commentable, only: [:index, :show]
  resources :attachments, only: [:destroy]
end

app/models/lensitem.rb
class Lensitem < ActiveRecord::Base
  include Commentable

  belongs_to :user
  belongs_to :lensmodel

  validates :price, presence: true, numericality:  { greater_than: 0 }
  validates :lensmodel_id, presence: true
  validates :user_id, presence: true
  # validates :description, length: { minimum: 2, maximum: 1000 }

  after_create  { increase_quantity }
  after_destroy { decrease_quantity }

  mount_uploader :image, ImageUploader

  private

  def increase_quantity
    lensmodel.update_attributes(quantity: lensmodel.quantity + 1)
  end

  def decrease_quantity
    lensmodel.update_attributes(quantity: lensmodel.quantity - 1)
  end
end

app/controllers/lensitems_controller.rb
class LensitemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_lensitem, only: [:show, :edit, :update, :destroy]

  authorize_resource
  # respond_to :js, :json

  def index
    respond_with(@lensitems = Lensitem.all)
  end

  def show
    @lensmodel = @lensitem.lensmodel
    respond_with @lensitem
  end

  def new
    @lensmodels = Lensmodel.order("frmin")
    respond_with(@lensitem = Lensitem.new)
  end

  def edit
  end

  def create
    respond_with(@lensitem = Lensitem.create(lensitem_params))
  end

  def update
    @lensitem.update(lensitem_params)
    respond_with @lensitem
  end

  def destroy
    @lensitem.destroy if @lensitem.user_id == current_user.id
    respond_with @lensitem
  end

  private

  def load_lensitem
    @lensitem = Lensitem.find(params[:id])
  end

  def lensitem_params
    params.require(:lensitem).permit(:lensmodel_id, :price, :description, :image, :used).merge(user_id: current_user.id)
  end
end

app/helpers/lensitems_helper.rb
module LensitemsHelper
end

app/views/lensitems/_form.html.slim
div
  = f.label :lensmodel_id
  = f.collection_select :lensmodel_id, @lensmodels, :id, :fullname, { prompt: true }
div
  = f.label "Цена:"
  = f.number_field :price, size: 61
  = f.label "Б/у"
  = f.check_box :used, size: 61
  = f.label "Видимый"
  = f.check_box :visible
div
  = f.label "Описание:"
  = f.text_field :description, size: 61
div
  = f.label "Изображение:"
  = f.file_field :image

app/views/lensitems/edit.html.slim
= form_for @lensitem do |f|
  = render partial: "form", locals: { f: f }
  = f.submit "Изменить объектив", class: 'btn btn-success btn-sm'

app/views/lensitems/index.html.slim
- unless @lensitems.empty?
  h1 Объективы:
  table class="table" id="lensitems"
    thead
      tr
        th Фото:
        th Mount:
        th Brand:
        th Наименование:
        th Цена:
        th min:
        th max:
        th min:
        th max:
    tbody
      - @lensitems.each do |lensitem|
        tr
          td = image_tag lensitem.image.thumb
          td = lensitem.lensmodel.mount
          td = lensitem.lensmodel.brand
          td = link_to (lensitem.lensmodel.name), lensitem_path(lensitem)
          td = link_to (lensitem.price), lensitem_path(lensitem)
          td = lensitem.lensmodel.frmin
          td = lensitem.lensmodel.frmax if lensitem.lensmodel.frmin != lensitem.lensmodel.frmax
          td = lensitem.lensmodel.diafmin
          td = lensitem.lensmodel.diafmax if lensitem.lensmodel.diafmin != lensitem.lensmodel.diafmax
- else
  h4 Нет объективов в продаже!

app/views/lensitems/new.html.slim
h1 Продать объектив:
= form_for @lensitem do |f|
  = render partial: "form", locals: { f: f }
  .lensitem-errors
  br
    = f.submit "Продать объектив", class: 'btn btn-success btn-sm'

app/views/lensitems/show.html.slim
h2
  i &nbsp;
  = link_to ('<< '), lensmodel_path(@lensmodel)
  = (@lensmodel.mount + ' ' + @lensmodel.brand + ' ' + @lensmodel.name)
br
- if can?(:update, @lensitem)
  = link_to "Редактировать?", edit_lensitem_path(@lensitem)
  i &nbsp; или &nbsp;
  = link_to "Удалить?", @lensitem, method: :delete, data: {confirm: "Подтверждение удаления"}
div
  i Цена:&nbsp;
  = @lensitem.price
  i &nbsp рублей
div
  i Б.у.:&nbsp;
  = @lensitem.used
div
  i Описание:&nbsp;
  = @lensitem.description
div
  i email:&nbsp
  = link_to (@lensitem.user.email), user_path(@lensitem.user_id)
div
  = image_tag @lensitem.image.normal
= render 'comments/list', parent: @lensitem