config/routes.rb
Rails.application.routes.draw do
  devise_scope(:user) { get '/users/sign_out' => 'devise/sessions#destroy' }
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'lensmodels#index'

  concern :commentable do
    resources :comments
  end

  resources :lensmodels,   concerns: :commentable, shallow: true
  resources :lensitems,    concerns: :commentable
  resources :cameramodels, concerns: :commentable
  resources :cameraitems,  concerns: :commentable
  resources :users,        concerns: :commentable, only: [:index, :show]
  resources :attachments, only: [:destroy]
end

app/models/lensmodel.rb
class Lensmodel < ActiveRecord::Base
  include Commentable
  has_many :lensitems, foreign_key: 'lensmodel_id', dependent: :destroy

  validates :brand,   presence: true, length:        { minimum: 2, maximum: 15 }
  validates :name,    presence: true, length:        { minimum: 2, maximum: 60 }
  validates :mount,   presence: true, length:        { minimum: 2, maximum: 10 }
  validates :frmin,   presence: true, numericality:  { greater_than: 0, less_than: 2000 }
  validates :frmax,   presence: true, numericality:  { greater_than: 0, less_than: 2000 }
  validates :diafmin, presence: true, numericality:  { greater_than: 0, less_than: 20 }
  validates :diafmax, presence: true, numericality:  { greater_than: 0, less_than: 20 }

  scope :only_sony,    -> { where(brand: 'SONY').order("frmin") }
  scope :only_samyang, -> { where(brand: 'Samyang') }
  scope :only_sigma,   -> { where(brand: 'Sigma') }
  scope :only_tamron,  -> { where(brand: 'Tamron') }
  scope :only_cz,      -> { where(brand: 'Carl Zeiss') }
  scope :only_minolta, -> { where(brand: 'MINOLTA') }
  scope :only_ff,      -> { where(ff: true) }
  scope :only_crop,    -> { where(ff: false) }
  scope :only_fix,     -> { where(fix: true) }
  scope :only_tele,    -> { where(fix: false) }
  scope :only_A,       -> { where(mount: 'A-mount') }
  scope :only_E,       -> { where(mount: 'E-mount') }

  def fullname
    "#{mount} #{brand} #{name}"
  end
end

app/controllers/lensmodels_controller.rb
class LensmodelsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_lensmodel, only: [:show, :edit, :update, :destroy]

  authorize_resource
  # respond_to :js, :json

  def index
    @cameramodels = Cameramodel.all
    respond_with(@lensmodels = Lensmodel.all)
  end

  def show
    @lensitems = @lensmodel.lensitems
    respond_with @lensmodel
  end

  def new
    respond_with(@lensmodel = Lensmodel.new)
  end

  def edit
  end

  def create
    respond_with(@lensmodel = Lensmodel.create(lensmodel_params))
  end

  def update
    @lensmodel.update(lensmodel_params)
    respond_with @lensmodel
  end

  def destroy
    respond_with(@lensmodel.destroy)
  end

  private

  def load_lensmodel
    @lensmodel = Lensmodel.find(params[:id])
  end

  def lensmodel_params
    params.require(:lensmodel).permit(:name, :brand, :mount, :frmin, :frmax, :diafmin, :diafmax, :ff, :fix, :afdrive, :macro, :weather, :link1, :link2)
  end
end

app/helpers/lensmodels_helper.rb
module LensmodelsHelper
end

app/views/lensmodels/_form.html.slim
div
  = f.label :mount
  = f.text_field :mount, size: 61
div
  = f.label :brand
  = f.text_field :brand, size: 61
div
  = f.label :name
  = f.text_field :name, size: 61
div
  = f.label :frmin
  = f.number_field :frmin
  = f.label :frmax
  = f.number_field :frmax
  = f.label :ff
  = f.check_box :ff
  = f.label :fix
  = f.check_box :fix
div
  = f.label :diafmin
  = f.number_field(:diafmin, in: 0.8..10.0, step: 0.1)
  = f.label :diafmax
  = f.number_field(:diafmax, in: 0.8..10.0, step: 0.1)
  = f.label :macro
  = f.check_box :macro
  = f.label :weather
  = f.check_box :weather
div
  = f.label :link1
  = f.text_field :link1, size: 61
div
  = f.label :link2
  = f.text_field :link2, size: 61

app/views/lensmodels/edit.html.slim
= form_for @lensmodel do |f|
  = render partial: "form", locals: { f: f }
  br
    = f.submit "Изменить объектив", class: 'btn btn-success btn-sm'

app/views/lensmodels/index.html.slim
- unless @lensmodels.empty?
  h1 Объективы:
  table class="table" id="lensmodels"
    thead
      tr
        th Mount:
        th Brand:
        th Наименование:
        th Кол-во:
        th min:
        th max:
        th min:
        th max:
    tbody
      - @lensmodels.each do |lensmodel|
        tr
          td = lensmodel.mount
          td = lensmodel.brand
          td = link_to (lensmodel.name), lensmodel_path(lensmodel)
          td = lensmodel.quantity
          td = lensmodel.frmin
          td = lensmodel.frmax if lensmodel.frmin != lensmodel.frmax
          td = lensmodel.diafmin
          td = lensmodel.diafmax if lensmodel.diafmin != lensmodel.diafmax
- else
  h4 Список пуст! зайди в rails консоль на сервере и добавь вручную!

app/views/lensmodels/new.html.slim
= form_for @lensmodel do |f|
  = render partial: "form", locals: { f: f }
  br
    = f.submit "Добавить объектив", class: 'btn btn-success btn-sm'

app/views/lensmodels/show.html.slim
- if can?(:create, Lensmodel)
  = link_to "Редактировать?", edit_lensmodel_path(@lensmodel)
  i &nbsp; или &nbsp;
  = link_to "Удалить?", @lensmodel, method: :delete, data: {confirm: "Подтверждение удаления"}
h2 = (@lensmodel.mount + ' ' + @lensmodel.brand + ' ' + @lensmodel.name + ' ' + @lensmodel.quantity.to_s)
- unless @lensitems.empty?
  table class="table" id="lensitems"
    thead
      tr
        th Фото:
        th Пользователь email:
        th Цена:
        th Создан:
        th Изменен:
    tbody
      - @lensitems.each do |lensitem|
        tr
          td = image_tag lensitem.image.thumb
          td = link_to (lensitem.user.email), user_path(lensitem.user_id)
          td = link_to (lensitem.price), lensitem_path(lensitem)
          td = lensitem.created_at.strftime("%d.%m.%Y")
          td = lensitem.updated_at.strftime("%d.%m.%Y") if lensitem.created_at != lensitem.updated_at
- else
  h4 Таких объективов в продаже пока НЕТ!

= render 'comments/list', parent: @lensmodel