config/routes.rb
Rails.application.routes.draw do
  devise_scope(:user) { get '/users/sign_out' => 'devise/sessions#destroy' }
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'lensmodels#index'

  concern :commentable do
    resources :comments
  end

  resources :lensmodels,   concerns: :commentable, shallow: true
  resources :lensitems,    concerns: :commentable
  resources :cameramodels, concerns: :commentable
  resources :cameraitems,  concerns: :commentable
  resources :users,        concerns: :commentable, only: [:index, :show]
  resources :attachments, only: [:destroy]
end

app/views/layouts/_banner.html.erb
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=33265193&amp;from=informer"
   target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/33265193/3_0_8686FFFF_6666FFFF_0_pageviews"
                                       style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:33265193,lang:'ru'});return false}catch(e){}" /></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script src="https://mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<script type="text/javascript">
    try {
        var yaCounter33265193 = new Ya.Metrika({
            id:33265193,
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
        });
    } catch(e) { }
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/33265193" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- begin of Top100 code -->
<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?3140660"></script>
<noscript>
  <a href="http://top100.rambler.ru/navi/3140660/">
    <img src="http://counter.rambler.ru/top100.cnt?3140660" alt="Rambler's Top100" border="0" />
  </a>
</noscript>
<!-- end of Top100 code -->

<!-- Rating@Mail.ru counter -->
<script type="text/javascript">
    var _tmr = window._tmr || (window._tmr = []);
    _tmr.push({id: "2703286", type: "pageView", start: (new Date()).getTime()});
    (function (d, w, id) {
        if (d.getElementById(id)) return;
        var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
        ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
        var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
        if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
    })(document, window, "topmailru-code");
</script><noscript><div style="position:absolute;left:-10000px;">
  <img src="//top-fwz1.mail.ru/counter?id=2703286;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->

<!-- Rating@Mail.ru logo -->
<a href="http://top.mail.ru/jump?from=2703286">
  <img src="//top-fwz1.mail.ru/counter?id=2703286;t=479;l=1"
       style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru" /></a>
<!-- //Rating@Mail.ru logo -->

<!--Openstat-->
<span id="openstat1"></span>
<script type="text/javascript">
    var openstat = { counter: 1, image: 87, color: "458efc", next: openstat };
    (function(d, t, p) {
        var j = d.createElement(t); j.async = true; j.type = "text/javascript";
        j.src = ("https:" == p ? "https:" : "http:") + "//openstat.net/cnt.js";
        var s = d.getElementsByTagName(t)[0]; s.parentNode.insertBefore(j, s);
    })(document, "script", document.location.protocol);
</script>
<!--/Openstat-->

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Lensprice"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"LENSPRICE.RU
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            - if current_user
              li = link_to "Продать объектив", new_lensitem_path
              li = link_to "Продать камеру", new_cameraitem_path
              li = link_to current_user.email, user_path(current_user)
              li = link_to "Выйти", destroy_user_session_path
            - else
              li = link_to "Войти", new_user_session_path
              li = link_to "Регистрация", new_user_registration_path
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 На сайте:
            ul.nav.nav-list
              li.nav-header Модели:
              li = link_to "Объективы #{Lensmodel.all.size}", lensmodels_path
              li = link_to "Камеры #{Cameramodel.all.size}", cameramodels_path
              li.nav-header В продаже:
              li = link_to "Все объективы #{Lensitem.all.size}", lensitems_path
              li = link_to "Все камеры #{Cameraitem.all.size}", cameraitems_path
              li.nav-header Пользователи:
              li = link_to "Все пользователи #{User.all.size}", users_path
              - if current_user
                - if can?(:create, [Lensmodel, Cameramodel])
                  li.nav-header Добавить в базу модель:
                  li = link_to "объектива", new_lensmodel_path
                  li = link_to "камеры", new_cameramodel_path

      footer
        i &copy; Lensprice 2015
        = render 'layouts/banner'